import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../../../infra/prisma/prisma.service';

@Injectable()
export class ExportUserDataUseCase {
  constructor(private readonly prisma: PrismaService) {}

  async execute(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId, deletedAt: null },
      select: {
        id: true,
        email: true,
        fullName: true,
        age: true,
        university: true,
        incomeType: true,
        averageMonthlyIncome: true,
        financialLiteracyLevel: true,
        profileCompleted: true,
        currency: true,
        consentGiven: true,
        consentAt: true,
        privacyPolicyVersion: true,
        termsVersion: true,
        consentIp: true,
        consentUserAgent: true,
        createdAt: true,
        updatedAt: true,
      },
    });

    if (!user) throw new NotFoundException('User not found');

    const [
      accounts,
      categories,
      transactions,
      budgets,
      goals,
      recommendations,
      surveyResponses,
      quizAttempts,
      topicProgress,
      financialProgress,
      feedback,
      notifications,
      conversations,
      analyticsEvents,
    ] = await Promise.all([
      this.prisma.account.findMany({
        where: { userId },
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          name: true,
          type: true,
          currency: true,
          openingBalance: true,
          creditLimit: true,
          institution: true,
          isDefault: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
        },
      }),
      this.prisma.category.findMany({
        where: { userId },
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          name: true,
          type: true,
          transactionType: true,
          icon: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
        },
      }),
      this.prisma.transaction.findMany({
        where: { userId },
        orderBy: { occurredAt: 'desc' },
        select: {
          id: true,
          categoryId: true,
          accountId: true,
          toAccountId: true,
          budgetId: true,
          type: true,
          currency: true,
          amount: true,
          description: true,
          occurredAt: true,
          suggestedCategoryId: true,
          aiConfidence: true,
          categorySource: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
        },
      }),
      this.prisma.budget.findMany({
        where: { userId },
        orderBy: [{ year: 'desc' }, { month: 'desc' }],
        select: {
          id: true,
          categoryId: true,
          name: true,
          amountLimit: true,
          month: true,
          year: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
        },
      }),
      this.prisma.savingsGoal.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          name: true,
          targetAmount: true,
          currentAmount: true,
          dueDate: true,
          completedAt: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
          contributions: {
            select: { id: true, amount: true, createdAt: true },
            orderBy: { createdAt: 'asc' },
          },
        },
      }),
      this.prisma.recommendation.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          type: true,
          message: true,
          suggestedAction: true,
          isActive: true,
          modelVersion: true,
          source: true,
          inputContextJson: true,
          viewedAt: true,
          dismissedAt: true,
          expiresAt: true,
          feedbackAccepted: true,
          feedbackAt: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      this.prisma.surveyResponse.findMany({
        where: { userId },
        orderBy: { completedAt: 'desc' },
        select: {
          id: true,
          surveyId: true,
          answersJson: true,
          score: true,
          completedAt: true,
          survey: { select: { type: true } },
        },
      }),
      this.prisma.quizAttempt.findMany({
        where: { userId },
        orderBy: { attemptedAt: 'desc' },
        select: {
          id: true,
          questionId: true,
          topicId: true,
          selectedAnswer: true,
          isCorrect: true,
          attemptedAt: true,
        },
      }),
      this.prisma.userTopicProgress.findMany({
        where: { userId },
        select: {
          id: true,
          topicId: true,
          score: true,
          attemptsCount: true,
          readAt: true,
          completedAt: true,
          createdAt: true,
        },
      }),
      this.prisma.userFinancialProgress.findMany({
        where: { userId },
        orderBy: { period: 'desc' },
        select: {
          id: true,
          period: true,
          budgetComplianceScore: true,
          savingsRatePct: true,
          overspendCategoriesCount: true,
          recommendationsShown: true,
          recommendationsAccepted: true,
          quizzesCompleted: true,
          avgQuizScore: true,
          createdAt: true,
        },
      }),
      this.prisma.feedback.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          type: true,
          message: true,
          screenName: true,
          rating: true,
          createdAt: true,
        },
      }),
      this.prisma.notification.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          type: true,
          title: true,
          body: true,
          data: true,
          readAt: true,
          sentAt: true,
          createdAt: true,
        },
      }),
      this.prisma.aiConversation.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          status: true,
          startedAt: true,
          endedAt: true,
          createdAt: true,
          updatedAt: true,
          messages: {
            orderBy: { createdAt: 'asc' },
            select: {
              id: true,
              role: true,
              content: true,
              feedbackRating: true,
              feedbackHelpful: true,
              feedbackClear: true,
              feedbackPersonalized: true,
              feedbackComment: true,
              feedbackAt: true,
              createdAt: true,
            },
          },
        },
      }),
      this.prisma.analyticsEvent.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          eventType: true,
          metadata: true,
          createdAt: true,
        },
      }),
    ]);

    return JSON.parse(JSON.stringify({
      exportedAt: new Date().toISOString(),
      privacyPolicyVersion: user.privacyPolicyVersion,
      termsVersion: user.termsVersion,
      profile: user,
      data: {
        accounts,
        categories,
        transactions,
        budgets,
        goals,
        recommendations,
        surveyResponses,
        quizAttempts,
        topicProgress,
        financialProgress,
        feedback,
        notifications,
        conversations,
        analyticsEvents,
      },
    }));
  }
}
